task30/zcart/routes/web.php
<?php
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('group', 'groupController');
Route::resource('subgroup', 'supGroupController');
Route::resource('category', 'categoryController');

task30/zcart/resources/views/addcategory.blade.php
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://use.fontawesome.com/d876aa8ccf.js"></script>
    <title>add category</title>
  </head>
  <body>
  <section class="container">
    <a href="{{ route('category.index') }}" class="btn btn-info">All categories</a>

    <form  method="post" action="{{isset($targetItem)? route('category.update', $targetItem) : route('category.store') }}">
        @csrf
        @isset ($targetItem)
            @method('PUT')
        @endif
        <div class="form-group">
            <label for='subgroup'>CATEGORY GROUP</label>
            <select name="supgroups_id" id="subgroup" class="form-control">
                <option >{{ isset($targetItem)? $targetItem->supgroups_id : 'select subgroup name'}}</option>
                @foreach($supgroups as $sub)
                <option value="{{ $sub->id }}"> {{ $sub->name }}</option>
                @endforeach
            </select>
        </div>
        <div class="form-group">
            <label for="title">category Name</label>
            <input type="text" id="title" name="name" class="form-control" value="{{ isset($targetItem)? $targetItem->name : '' }}">
        </div>
        <div class="form-group">
            <label for="body">Description</label>
            <textarea name="description" id="body" cols="30" rows="10" class="form-control" >{{ isset($targetItem)? $targetItem->description  : '' }}</textarea>
        </div>

        <div class="text-center">
            <button type="submit" class="btn btn-success">{{ isset($targetItem)? 'Update' : 'Save' }}</button>
        </div>
    </form>
</section>
  </body>
</html>

task30/zcart/resources/views/addgroup.blade.php
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://use.fontawesome.com/d876aa8ccf.js"></script>
    <title>add group</title>
  </head>
  <body>
  <section class="container">
    
      <a href="{{ route('group.index') }}" class="btn btn-info mt-5 mb-3">All groups</a>

      <form  method="post" action="{{isset($targetItem)? route('group.update', $targetItem) : route('group.store') }}">
        @csrf
        @isset ($targetItem)
            @method('PUT')
        @endif
        <div class="form-group">
            <label for="title">Group Name</label>
            <input type="text" id="title" name="name" class="form-control" value="{{ isset($targetItem)? $targetItem->name : '' }}">
        </div>
        <div class="form-group">
            <label for="body">Description</label>
            <textarea name="description" id="body" cols="30" rows="10" class="form-control" >{{ isset($targetItem)? $targetItem->description  : '' }}</textarea>
        </div>

        <div class="text-center">
            <button type="submit" class="btn btn-success">{{ isset($targetItem)? 'Update' : 'Save' }}</button>
        </div>
      </form>
    
</section>
  </body>
</html>

task30/zcart/resources/views/addsubgroup.blade.php
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://use.fontawesome.com/d876aa8ccf.js"></script>
    <title>add and update sub-group</title>
  </head>
  <body>
  <section class="container">
    <a href="{{ route('subgroup.index') }}" class="btn btn-info">All sub_groups</a>

    <form  method="post" action="{{isset($targetItem)? route('subgroup.update', $targetItem) : route('subgroup.store') }}">

        @csrf
        @isset ($targetItem)
            @method('PUT')
        @endif
        <div class="form-group">
            <label for="group">CATEGORY GROUP</label>
            <select name="groups_id" id="group" class="form-control">
                <option >{{ isset($targetItem)? $targetItem->groups_id :'select group name'}}</option>
                @foreach($group as $sub)
                    
                    <option value="{{ $sub->id }}"> {{ $sub->name }}</option>
                @endforeach
            </select>
        </div>
        <div class="form-group">
            <label for="title">sub-group Name</label>
            <input type="text" id="title" name="name" class="form-control" value="{{ isset($targetItem)? $targetItem->name : '' }}">
        </div>
        <div class="form-group">
            <label for="body">Description</label>
            <textarea name="description" id="body" cols="30" rows="10" class="form-control" >{{ isset($targetItem)? $targetItem->description  : '' }}</textarea>
        </div>

        <div class="text-center">
            <button type="submit" class="btn btn-success">{{ isset($targetItem)? 'Update' : 'Save' }}</button>
        </div>
    </form>
</section>
  </body>
</html>

task30/zcart/resources/views/category.blade.php
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://use.fontawesome.com/d876aa8ccf.js"></script>
    <title>Hello, world!</title>
  </head>
  <body>
 
    <div class="container bg-light">
      <div class="d-flex justify-content-between mt-5 mb-3 pt-2">
        <h5>CATEGORIES</h5>
        <a href="{{route('category.create')}}" class="btn btn-dark">ADD CATEGORY </a>
      </div>
      <table class="table">
        <thead>
          <tr>
            <th scope="col">ID</th>
            <th scope="col">Category name</th>
            <th scope="col">Category description</th>
            <th scope="col">subgroup</th>
          </tr>
        </thead>
        <tbody>
          @foreach($category as $item)
            <tr>
              <th scope="row">{{$item->id}}</th>
              <td>{{$item->name}}</td>
              <td>{{$item->description}}</td>
              <td>{{$item->supgroups_id}}</td>
              <td>
                <a href="{{ route('category.edit', $item) }}" style="color:black "><i class="fa fa-pencil-square-o" aria-hidden="true"></i> </a>
   
                <form method="post"style="display: inline-block" action="{{ route('category.destroy', $item) }}">
                    @method('DELETE')
                    @csrf
                  <button style="color:black ; border:none"><i class="fa fa-trash" aria-hidden="true"></i></button>
                </form>
              </td>
            </tr>
          @endforeach
        </tbody>
      </table>
    </div>


  
  </body>
</html>

task30/zcart/resources/views/group.blade.php
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://use.fontawesome.com/d876aa8ccf.js"></script>
    <title>Hello, world!</title>
  </head>
  <body>
 
  <div class="container bg-light">
    <div class="d-flex justify-content-between mt-5 mb-3 pt-2">
      <h5 >CATEGORY GROUPS</h5>
      <a href="{{route('group.create')}}" class="btn btn-dark">ADD CATEGORY GROUP</a>
    </div>
    <table class="table">
      <thead>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">group name</th>
          <th scope="col">group description</th>
        </tr>
      </thead>
      <tbody>
        @foreach($group as $item)
          <tr>
    
            <th scope="row">{{$item->id}}</th>
            <td>{{$item->name}}</td>
            <td>{{$item->description}}</td>
            <td>
              <a href="{{ route('group.edit', $item) }}" style="color:black "><i class="fa fa-pencil-square-o" aria-hidden="true"></i> </a>
  
              <form method="post"style="display: inline-block" action="{{ route('group.destroy', $item) }}">
                   @method('DELETE')
                   @csrf
                <button style="color:black ; border:none"><i class="fa fa-trash" aria-hidden="true"></i></button>
              </form>
     
            </td>
          </tr>
          @endforeach
        </tbody>
      </table>
    </div>


   
  </body>
</html>

task30/zcart/resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

task30/zcart/resources/views/subgroup.blade.php
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://use.fontawesome.com/d876aa8ccf.js"></script>
    <title>Hello, world!</title>
  </head>
  <body>
 
  <div class="container bg-light">
    <div class="d-flex justify-content-between mt-5 mb-3 pt-2">
      <h5>CATEGORY SUB-GROUPS</h5>
      <a href="{{ route('subgroup.create') }}" class="btn btn-dark">ADD CATEGORY SUB-GROUP</a>
    </div>
    <table class="table">
        <thead>
          <tr>
            <th scope="col">ID</th>
            <th scope="col">subgroup name</th>
            <th scope="col">supgroup description</th>
            <th scope="col">group</th>
          </tr>
        </thead>
        <tbody>
          @foreach($subgroup as $item)
          <tr>
            <th scope="row">{{$item->id}}</th>
            <td>{{$item->name}}</td>
            <td>{{$item->description}}</td>
            <td>{{$item->groups_id}}</td>

            <td>
              <a href="{{ route('subgroup.edit', $item) }}" style="color:black "><i class="fa fa-pencil-square-o" aria-hidden="true"></i> </a>
   
              <form method="post"style="display: inline-block" action="{{ route('subgroup.destroy', $item) }}">
                    @method('DELETE')
                    @csrf
              <button style="color:black ; border:none"><i class="fa fa-trash" aria-hidden="true"></i></button>
              </form>
            </td>
          </tr>
          @endforeach
       </tbody>
      </table>
    </div>

  </body>
</html>